spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/microservices}
    username: ${SPRING_DATASOURCE_USERNAME:microservices}
    password: ${SPRING_DATASOURCE_PASSWORD:microservices}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    sql:
      init:
        mode: always

server:
  port: ${APP_SERVER_PORT:8080}
  servlet:
    context-path: ${APP_SERVER_CONTEXT_PATH:/}