services:
  produit:
    build:
      context: produit
    container_name: produit
    ports:
      - 8080:8080
      - 12355:12355
    environment:
      SPRING_DATASOURCE_USERNAME: microservices
      SPRING_DATASOURCE_PASSWORD: microservices
    depends_on:
      - db
    networks:
      - spring-postgres
  cart:
    build:
      context: cart
    container_name: cart
    ports:
      - 8081:8081
      - 12356:12355
    environment:
      SPRING_DATASOURCE_USERNAME: microservices
      SPRING_DATASOURCE_PASSWORD: microservices
    depends_on:
      - db
    networks:
      - spring-postgres
  commande:
    build:
      context: commande
    container_name: commande
    ports:
      - 8082:8082
      - 12357:12355
    environment:
      SPRING_DATASOURCE_USERNAME: microservices
      SPRING_DATASOURCE_PASSWORD: microservices
    depends_on:
      - db
    networks:
      - spring-postgres
  db:
    image: postgres
    restart: always
    container_name: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
        POSTGRES_USER: microservices
        POSTGRES_PASSWORD: microservices
        POSTGRES_DB: microservices

    expose:
      - 5432

volumes:
  db-data:

networks:
  spring-postgres: